language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
script:
  - yarn dll
  - yarn install
  - yarn build
services:
  - docker
after_success:
  - docker build -t $IMAGE_NAME .
  - echo "$TOKEN" | docker login  docker.pkg.github.com --username b1412 --password-stdin
  - docker tag $IMAGE_NAME:latest docker.pkg.github.com/b1412/permission-ui/$IMAGE_NAME:$TRAVIS_BUILD_NUMBER
  - docker push docker.pkg.github.com/b1412/permission-ui/$IMAGE_NAME:$TRAVIS_BUILD_NUMBER
env:
  global:
    - IMAGE_NAME=permission-ui
