language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
script:
  - yarn dll
  - yarn install
  - yarn build
services:
  - docker
after_success:
  - docker build -t $REPO/$IMAGE_NAME .
  - echo "$TOKEN" | docker login  docker.pkg.github.com --username $DOCKER_USERNAME --password-stdin
  - docker tag $REPO/$IMAGE_NAME:latest $REPO/$IMAGE_NAME:$TRAVIS_BUILD_NUMBER
  - docker push $REPO/$IMAGE_NAME:latest
  - docker push $REPO/$IMAGE_NAME:$TRAVIS_BUILD_NUMBER
env:
  global:
    - IMAGE_NAME=permission-ui
    - REPO=docker.pkg.github.com/b1412/permission-ui
    - DOCKER_USERNAME=b1412
